name: build

on:
  push:
    branches: ['*']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install
      - run: yarn download
      - run: cp .env.example .env
      - run: npx ganache-cli > /dev/null &
      - run: npm run migrate:dev
      - run: yarn test
      - run: node src/cli.js test
      - run: yarn lint
      - run: yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
